baseURL = "https://blog.safenetwork.org/"
title = "SAFE Network Blog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper3"

[params]
  facebook = "https://www.facebook.com/safenetworktech"
  twitter = "https://twitter.com/safenetworktech"
  reddit = "https://www.reddit.com/r/safenetwork/"
  description = "Blog posts written by members of the SAFE Network community"
  mainSections = ["post"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://safenetwork.tech/"
    weight = 10
  [[menu.main]]
    identifier = "forum"
    name = "Community Forum"
    url = "https://safenetforum.org/"
    weight = 20
  [[menu.main]]
    identifier = "github-repo"
    name = "Contribute on GitHub"
    url = "https://github.com/safenetwork/blog.safenetwork.org"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.twitter]
    disableInlineCSS = true
