enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.twitter]
disabled = false
enableDNT = true
simple = true
disableInlineCSS = true

[privacy.youtube]
disabled = false
privacyEnhanced = true
